# Generated by Django 3.2.7 on 2022-11-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Branch',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Hostel_Room_No',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Hosteler_or_DayScholar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Languages_Known',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Native_Language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Section',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='foreigners_can_enter_their_states_here',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='year_joined',
        ),
    ]
