# Generated by Django 3.2.7 on 2022-11-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
