# Generated by Django 3.2.7 on 2022-11-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userpost_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
