# Generated by Django 3.2.7 on 2022-11-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20221123_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='field',
        ),
        migrations.RemoveField(
            model_name='page',
            name='website',
        ),
        migrations.RemoveField(
            model_name='page',
            name='your_role',
        ),
    ]
