# Generated by Django 3.2.7 on 2022-11-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveapitokenmodel',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
