# Generated by Django 3.2.7 on 2022-11-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_usermoviesavemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermoviesavemodel',
            old_name='title',
            new_name='imdbid',
        ),
        migrations.AddField(
            model_name='usermoviesavemodel',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
